[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sda"
version = "0.0.1"
description = "Submodule package for SDA experiments"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "numpy",
  "torch",
  "h5py",
  "dawgz",
  "matplotlib",
  "tqdm",
  "zuko",
  "wandb",
  "seaborn",
  "pillow",
  "rich>=14.2.0",
  "structlog>=25.5.0",
  "pydantic>=2.12.5",
  "pydantic-settings>=2.12.0",
]

[tool.setuptools]
packages = ["sda"]  # sda/ 配下に __init__.py がある前提
